// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdhdccljoezhykoqnvuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kaGRjY2xqb2V6aHlrb3FudnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjkyMDAsImV4cCI6MjA2NDI0NTIwMH0.gLfh9-ESH_TEdCDNKJlNMhCAccpl8HfyEdpK35BdRqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);